### ISSUE TITLE
Fleshing out the experiment branch

### ISSUE THREAD

**Issue by schasins** [gelinasj/web-to-kg#1]
Hi!  Could you go ahead and `git add` the build script for the experiment branch?  (And perhaps just generally check that all required files are git added.)  It would also be awesome if you could add a README explaining (1) how to build the extension and (2) which directory to treat as the root directory for loading the unpacked extension in Chrome!

**Comment by gelinasj** [comment]
Just finished!

Commits:
f0142857f561d7578ae2a91e8c751a5dbd500894
9539d5ba847abca2b54f25956b3d3ecd643f658d
